/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import sistemaacademia.Membro;
import javax.swing.JOptionPane;
import sistemaacademia.MembroDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.Color;



/**
 *
 * @author FARIAS
 */
public class CadastroMembro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroMembro.class.getName());

    /**
     * Creates new form CadastroMembro
     */
    public CadastroMembro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nometxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpftxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        confirmarsenhatxt = new javax.swing.JPasswordField();
        telefonetxt = new javax.swing.JTextField();
        senhatxt = new javax.swing.JPasswordField();
        emailtxt = new javax.swing.JTextField();
        botãocadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        termoschk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("tela de cadastro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 394));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nometxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nometxt.setForeground(new java.awt.Color(204, 204, 204));
        nometxt.setText("Nome");
        nometxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        nometxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nometxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nometxtFocusLost(evt);
            }
        });
        nometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxtActionPerformed(evt);
            }
        });
        getContentPane().add(nometxt);
        nometxt.setBounds(90, 100, 170, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Confirmar:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 260, 80, 20);

        cpftxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpftxt.setForeground(new java.awt.Color(204, 204, 204));
        cpftxt.setText("CPF");
        cpftxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cpftxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpftxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpftxtFocusLost(evt);
            }
        });
        cpftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpftxtActionPerformed(evt);
            }
        });
        getContentPane().add(cpftxt);
        cpftxt.setBounds(90, 130, 170, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 230, 70, 20);
        getContentPane().add(confirmarsenhatxt);
        confirmarsenhatxt.setBounds(110, 260, 170, 20);

        telefonetxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefonetxt.setForeground(new java.awt.Color(204, 204, 204));
        telefonetxt.setText("Telefone");
        telefonetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        telefonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonetxtFocusLost(evt);
            }
        });
        telefonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonetxtActionPerformed(evt);
            }
        });
        getContentPane().add(telefonetxt);
        telefonetxt.setBounds(90, 190, 170, 20);

        senhatxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhatxtFocusGained(evt);
            }
        });
        senhatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhatxtActionPerformed(evt);
            }
        });
        getContentPane().add(senhatxt);
        senhatxt.setBounds(90, 230, 170, 20);

        emailtxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(204, 204, 204));
        emailtxt.setText("E-mail");
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });
        getContentPane().add(emailtxt);
        emailtxt.setBounds(90, 160, 170, 20);

        botãocadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botãocadastrar.setText("Cadastrar");
        botãocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãocadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botãocadastrar);
        botãocadastrar.setBounds(110, 320, 130, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("CADASTRE-SE");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 40, 180, 60);

        termoschk.setBackground(java.awt.SystemColor.windowBorder);
        termoschk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        termoschk.setForeground(new java.awt.Color(204, 204, 204));
        termoschk.setText("Política de Privacidade e Termos de Uso");
        termoschk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        termoschk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termoschkActionPerformed(evt);
            }
        });
        getContentPane().add(termoschk);
        termoschk.setBounds(50, 290, 250, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BACKGROUD 2.png"))); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxtActionPerformed

    private void botãocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãocadastrarActionPerformed
        // TODO add your handling code here:
        String senha = new String(senhatxt.getPassword());
        String confirmar = new String(confirmarsenhatxt.getPassword());
        
        if (nometxt.getText().isEmpty() ||
        cpftxt.getText().isEmpty() ||
        emailtxt.getText().isEmpty() ||
        telefonetxt.getText().isEmpty() ||
        senhatxt.getPassword().length == 0 ||
        confirmarsenhatxt.getPassword().length == 0) {
         
       JOptionPane.showMessageDialog(null, "Campos vazios");
    }
        
    if  (!termoschk.isSelected()) {
        JOptionPane.showMessageDialog(this, "Você precisa aceitar os termos.");
        return;
    }
    
    if (!senha.equals(confirmar)) {
        JOptionPane.showMessageDialog(this, "As senhas não coincidem.");
        return;
    }
        
        Membro m = new Membro();
        m.setNome(nometxt.getText());
        m.setCpf(cpftxt.getText());
        m.setEmail(emailtxt.getText());
        m.setTelefone(telefonetxt.getText());
        m.setSenha(senha);
        
        
        String hoje = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        m.setDataCadastro(hoje);
        
        
       
        MembroDAO dao = new MembroDAO();
        dao.inserirMembro(m);
        JOptionPane.showMessageDialog(null, "Membro " +nometxt.getText() + "foi cadastrado com sucesso!");
    
    nometxt.setText("");
    cpftxt.setText("");
    emailtxt.setText("");
    telefonetxt.setText("");
    senhatxt.setText("");
    confirmarsenhatxt.setText("");
    termoschk.setSelected(false);
    
    }//GEN-LAST:event_botãocadastrarActionPerformed

    private void cpftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpftxtActionPerformed

    private void telefonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonetxtActionPerformed

    private void termoschkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termoschkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termoschkActionPerformed

    private void jLabel1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentMoved

    private void nometxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nometxtFocusGained
        // TODO add your handling code here:
        if (nometxt.getText().equals("Nome")) {
           nometxt.setText("");
           nometxt.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_nometxtFocusGained

    private void nometxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nometxtFocusLost
        // TODO add your handling code here:
        if (nometxt.getText().isEmpty()) {
         nometxt.setForeground(Color.GRAY);
         nometxt.setText("Nome");
}
    }//GEN-LAST:event_nometxtFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nometxt.setText("Nome");
        nometxt.setForeground(Color.GRAY);
        
         cpftxt.setText("CPF");
         cpftxt.setForeground(Color.GRAY);
         
         emailtxt.setText("E-mail");
         emailtxt.setForeground(Color.GRAY);
         
         telefonetxt.setText("Telefone");
         telefonetxt.setForeground(Color.GRAY);
         
        
    }//GEN-LAST:event_formWindowOpened

    private void cpftxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpftxtFocusGained
        // TODO add your handling code here:
         if (cpftxt.getText().equals("CPF")) {
           cpftxt.setText("");
           cpftxt.setForeground(Color.BLACK);
         }
    }//GEN-LAST:event_cpftxtFocusGained

    private void cpftxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpftxtFocusLost
        // TODO add your handling code here:
         if (cpftxt.getText().isEmpty()) {
         cpftxt.setForeground(Color.GRAY);
         cpftxt.setText("CPF");
}
    }//GEN-LAST:event_cpftxtFocusLost

    private void emailtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusGained
        // TODO add your handling code here:
         if (emailtxt.getText().equals("E-mail")) {
           emailtxt.setText("");
           emailtxt.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_emailtxtFocusGained

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
        // TODO add your handling code here:
         if (emailtxt.getText().isEmpty()) {
         emailtxt.setForeground(Color.GRAY);
         emailtxt.setText("E-mail");
}
    }//GEN-LAST:event_emailtxtFocusLost

    private void telefonetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonetxtFocusGained
        // TODO add your handling code here:
        if (telefonetxt.getText().equals("Telefone")) {
           telefonetxt.setText("");
           telefonetxt.setForeground(Color.BLACK);
         }
    }//GEN-LAST:event_telefonetxtFocusGained

    private void telefonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonetxtFocusLost
        // TODO add your handling code here:
         if (telefonetxt.getText().isEmpty()) {
         telefonetxt.setForeground(Color.GRAY);
         telefonetxt.setText("Telefone");
}
    }//GEN-LAST:event_telefonetxtFocusLost

    private void senhatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhatxtActionPerformed

    private void senhatxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhatxtFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_senhatxtFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroMembro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãocadastrar;
    private javax.swing.JPasswordField confirmarsenhatxt;
    private javax.swing.JTextField cpftxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nometxt;
    private javax.swing.JPasswordField senhatxt;
    private javax.swing.JTextField telefonetxt;
    private javax.swing.JCheckBox termoschk;
    // End of variables declaration//GEN-END:variables
}
