/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import sistemaacademia.Funcionario;
import sistemaacademia.FuncionarioDAO;

/**
 *
 * @author FARIAS
 */
public class LoginFuncionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFuncionarios.class.getName());

    /**
     * Creates new form LoginFuncionarios
     */
    public LoginFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrarsenhachk = new javax.swing.JCheckBox();
        logintxt = new javax.swing.JTextField();
        senhatxt = new javax.swing.JPasswordField();
        botãobtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tela de login");
        setMinimumSize(new java.awt.Dimension(700, 394));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        mostrarsenhachk.setForeground(new java.awt.Color(204, 204, 204));
        mostrarsenhachk.setText("Mostrar senha");
        mostrarsenhachk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarsenhachkActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarsenhachk);
        mostrarsenhachk.setBounds(420, 220, 110, 20);

        logintxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logintxt.setForeground(new java.awt.Color(204, 204, 204));
        logintxt.setText("Login");
        logintxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        logintxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                logintxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                logintxtFocusLost(evt);
            }
        });
        getContentPane().add(logintxt);
        logintxt.setBounds(400, 140, 200, 30);

        senhatxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhatxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhatxtFocusLost(evt);
            }
        });
        getContentPane().add(senhatxt);
        senhatxt.setBounds(400, 180, 200, 30);

        botãobtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botãobtn.setText("Entrar");
        botãobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botãobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãobtnActionPerformed(evt);
            }
        });
        getContentPane().add(botãobtn);
        botãobtn.setBounds(440, 250, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BACKGROUND login (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 394);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logintxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logintxtFocusGained
        // TODO add your handling code here:
        if (logintxt.getText().equals("Login")) {
           logintxt.setText("");
           logintxt.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_logintxtFocusGained

    private void logintxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logintxtFocusLost
        // TODO add your handling code here:
        if (logintxt.getText().isEmpty()) {
         logintxt.setForeground(Color.GRAY);
         logintxt.setText("Login");
}
    }//GEN-LAST:event_logintxtFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        logintxt.setText("Login");
        logintxt.setForeground(Color.GRAY);
        
        senhatxt.setText("Senha");
        senhatxt.setForeground(Color.GRAY);
    }//GEN-LAST:event_formWindowOpened

    private void botãobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãobtnActionPerformed
        // TODO add your handling code here:
        String login = logintxt.getText();
        String senha = new String(senhatxt.getPassword());

if (login.isEmpty() || senha.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Preencha login e senha.");
    return;
}

FuncionarioDAO dao = new FuncionarioDAO();

if (dao.autenticar(login, senha)) {
    Funcionario f = dao.buscarFuncionario(login); 
    JOptionPane.showMessageDialog(this, "Bem-vindo, " + f.getNome() + "! Cargo: " + f.getCargo());
} else {
    JOptionPane.showMessageDialog(this, "Login ou senha inválidos.");
}

 logintxt.setText("");
 senhatxt.setText("");

    }//GEN-LAST:event_botãobtnActionPerformed

    private void senhatxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhatxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_senhatxtFocusGained

    private void mostrarsenhachkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarsenhachkActionPerformed
        // TODO add your handling code here:
        if (mostrarsenhachk.isSelected()) {
    senhatxt.setEchoChar((char) 0); 
} else {
    senhatxt.setEchoChar('•'); 
}

    }//GEN-LAST:event_mostrarsenhachkActionPerformed

    private void senhatxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhatxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_senhatxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFuncionarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField logintxt;
    private javax.swing.JCheckBox mostrarsenhachk;
    private javax.swing.JPasswordField senhatxt;
    // End of variables declaration//GEN-END:variables
}
