/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemaacademia.Pagamento;
import sistemaacademia.PagamentoDAO;

/**
 *
 * @author FARIAS
 */
public class RegistroPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroPagamento.class.getName());
    
    private java.util.List<sistemaacademia.Pagamento> listaAtual;


    /**
     * Creates new form RegistroPagamento
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public RegistroPagamento() {
        initComponents();
        carregarPagamentos();
        
    }
    
    

    
    public void carregarPagamentos() { 
    DefaultTableModel modelo = (DefaultTableModel) tabelaPagamentos.getModel();
    modelo.setRowCount(0); 

    PagamentoDAO dao = new PagamentoDAO();
    
    listaAtual = dao.listarPagamentos(); 

    for (Pagamento p : listaAtual) {
        modelo.addRow(new Object[]{
            "R$ " + String.format("%.2f", p.getValor()),
            formatarData(p.getDataPagamento()),
            p.getStatus()
        });
    }
}

    
    public String formatarData(String data) {
    LocalDate d = LocalDate.parse(data);
    return d.format(DateTimeFormatter.ofPattern("dd MMM yyyy", new Locale("pt", "BR")));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        campoBusca = new javax.swing.JTextField();
        botaoPagar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPagamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 394));
        getContentPane().setLayout(null);
        getContentPane().add(campoBusca);
        campoBusca.setBounds(160, 130, 380, 22);

        botaoPagar.setText("Pagar");
        botaoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPagarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPagar);
        botaoPagar.setBounds(570, 170, 100, 30);

        botaoBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscar);
        botaoBuscar.setBounds(570, 130, 100, 30);

        tabelaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Valor", "Data de Pagamento", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPagamentos.setColumnSelectionAllowed(true);
        tabelaPagamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelaPagamentos);
        tabelaPagamentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 150, 380, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BACKGROUND mensalidade (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 394);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPagarActionPerformed
        // TODO add your handling code here:
     int linhaSelecionada = tabelaPagamentos.getSelectedRow();

if (linhaSelecionada != -1) {
    TelaPagamento tela = new TelaPagamento(tabelaPagamentos, listaAtual);
tela.setVisible(true);

} else {
    JOptionPane.showMessageDialog(this, "Selecione um pagamento da tabela.");
}



        
       
    }//GEN-LAST:event_botaoPagarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        // TODO add your handling code here:
      String nome = campoBusca.getText().trim();

if (nome.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Digite o nome do membro.");
    return;
}

PagamentoDAO dao = new PagamentoDAO();
listaAtual = dao.buscarPagamentosPorNome(nome); 

DefaultTableModel modelo = (DefaultTableModel) tabelaPagamentos.getModel();
modelo.setRowCount(0); 

for (Pagamento p : listaAtual) {
    modelo.addRow(new Object[] {
        "R$ " + String.format("%.2f", p.getValor()),
        p.getDataPagamento(),
        p.getStatus()
    });
}


    }//GEN-LAST:event_botaoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroPagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoPagar;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPagamentos;
    // End of variables declaration//GEN-END:variables
}
