/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sistemaacademia.Pagamento;
import sistemaacademia.PagamentoDAO;


/**
 *
 * @author FARIAS
 */
public class TelaPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPagamento.class.getName());

    /**
     * Creates new form TelaPagamento
     */
    private final javax.swing.JTable tabelaPagamentos;
    private final java.util.List<sistemaacademia.Pagamento> listaAtual;

    public TelaPagamento(JTable tabela, java.util.List<sistemaacademia.Pagamento> lista) {
        initComponents();
        this.tabelaPagamentos = tabela;
        this.listaAtual = lista;
    }

    
   


    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPagamento = new javax.swing.JComboBox<>();
        botaoConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        comboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Cartão", "Boleto", " " }));
        comboPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(comboPagamento);
        comboPagamento.setBounds(100, 130, 200, 30);

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmar);
        botaoConfirmar.setBounds(140, 180, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/a.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -30, 490, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPagamentoActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        // TODO add your handling code here:
try {
    int linha = tabelaPagamentos.getSelectedRow();
    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Nenhum pagamento selecionado.");
        return;
    }

    Pagamento selecionado = listaAtual.get(linha);
    int idPagamento = selecionado.getId();

    String tipo = comboPagamento.getSelectedItem().toString();
    String dataHoje = java.time.LocalDate.now().toString(); 

    PagamentoDAO dao = new PagamentoDAO();
    dao.atualizarStatusParaPago(idPagamento, dataHoje);

    selecionado.setStatus("PAGO");
    selecionado.setDataPagamento(dataHoje);

  
    tabelaPagamentos.setValueAt("PAGO", linha, 2);
    tabelaPagamentos.setValueAt(dataHoje, linha, 1);

    JOptionPane.showMessageDialog(null, "Pagamento atualizado como PAGO via " + tipo + "!");
    dispose();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Erro ao atualizar pagamento: " + e.getMessage());
}



    }//GEN-LAST:event_botaoConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JComboBox<String> comboPagamento;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
