/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import sistemaacademia.Historico;
import sistemaacademia.HistoricoDAO;
/**
 *
 * @author FARIAS
 */
public class TelaCadastroHistorico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroHistorico.class.getName());

    /**
     * Creates new form TelaCadastroHistorico
     */
    private final int idMembro; 

    public TelaCadastroHistorico(int idMembro) {
        initComponents();
        this.idMembro = idMembro;
        setLocationRelativeTo(null);
        setSize(404, 335); 
        setResizable(false); 
        setLocationRelativeTo(null); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoAtividade = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        campoData = new javax.swing.JTextField();
        campoTempo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        campoAtividade.setText("Atividade");
        campoAtividade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoAtividadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAtividadeFocusLost(evt);
            }
        });
        getContentPane().add(campoAtividade);
        campoAtividade.setBounds(110, 90, 170, 22);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(150, 210, 90, 30);

        campoData.setText("Data");
        campoData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataFocusLost(evt);
            }
        });
        getContentPane().add(campoData);
        campoData.setBounds(110, 130, 170, 22);

        campoTempo.setText("Tempo");
        campoTempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTempoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTempoFocusLost(evt);
            }
        });
        getContentPane().add(campoTempo);
        campoTempo.setBounds(110, 170, 170, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/POPUP histórico.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 401, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String atividade = campoAtividade.getText().trim();
        String data = campoData.getText().trim();
        String tempo = campoTempo.getText().trim();

        if (atividade.isEmpty() || data.isEmpty() || tempo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        Historico h = new Historico();
        h.setIdMembro(idMembro);
        h.setAtividade(atividade);
        h.setDataAtividade(data);
        h.setTempoExecucao(tempo);

        new HistoricoDAO().inserir(h);

        JOptionPane.showMessageDialog(this, "Histórico cadastrado com sucesso!");
        this.dispose();
    
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void campoAtividadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAtividadeFocusGained
        // TODO add your handling code here:
        if (campoAtividade.getText().equals("Atividade")) {
           campoAtividade.setText("");
           campoAtividade.setForeground(Color.BLACK);
}

    }//GEN-LAST:event_campoAtividadeFocusGained

    private void campoAtividadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAtividadeFocusLost
        // TODO add your handling code here:
        if (campoAtividade.getText().isEmpty()) {
         campoAtividade.setForeground(Color.GRAY);
         campoAtividade.setText("Atividade");
}
    }//GEN-LAST:event_campoAtividadeFocusLost

    private void campoDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFocusGained
        // TODO add your handling code here:
        if (campoData.getText().equals("Data")) {
           campoData.setText("");
           campoData.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoDataFocusGained

    private void campoDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFocusLost
        // TODO add your handling code here:
        if (campoData.getText().isEmpty()) {
         campoData.setForeground(Color.GRAY);
         campoData.setText("Data");
}
    }//GEN-LAST:event_campoDataFocusLost

    private void campoTempoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTempoFocusGained
        // TODO add your handling code here:
        if (campoTempo.getText().equals("Tempo")) {
           campoTempo.setText("");
           campoTempo.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoTempoFocusGained

    private void campoTempoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTempoFocusLost
        // TODO add your handling code here:
        if (campoTempo.getText().isEmpty()) {
         campoTempo.setForeground(Color.GRAY);
         campoTempo.setText("Tempo");
}
    }//GEN-LAST:event_campoTempoFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        campoAtividade.setText("Atividade");
        campoAtividade.setForeground(Color.GRAY);
        
        campoData.setText("Data");
        campoData.setForeground(Color.GRAY);
        
        campoTempo.setText("Tempo");
        campoTempo.setForeground(Color.GRAY);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroHistorico(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField campoAtividade;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoTempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
