/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemaacademia.Historico;
import sistemaacademia.HistoricoDAO;


/**
 *
 * @author FARIAS
 */
public class TelaHistorico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaHistorico.class.getName());

    /**
     * Creates new form TelaHistorico
     */
    
    private int idMembroAtual = -1; 
    private List<Historico> listaAtual; 
    
    public TelaHistorico() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(700, 430); 
        setResizable(false); 
        setLocationRelativeTo(null); 
    }
    
    private void carregarTabela(List<Historico> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaHistorico.getModel();
        modelo.setRowCount(0); // limpa a tabela

        for (Historico h : lista) {
            modelo.addRow(new Object[]{
                h.getAtividade(),
                h.getDataAtividade(),
                h.getTempoExecucao()
            });
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHistorico = new javax.swing.JTable();
        campoBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 394));
        setPreferredSize(new java.awt.Dimension(700, 394));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tabelaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Atividade", "Data", "Tempo Execução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaHistorico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(52, 152, 600, 190);

        campoBusca.setText("Nome");
        campoBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoBuscaFocusLost(evt);
            }
        });
        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(campoBusca);
        campoBusca.setBounds(60, 130, 290, 22);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(60, 350, 72, 23);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(460, 350, 90, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(560, 350, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Histórico de atividade BG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 701, 394);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
        String termo = campoBusca.getText().trim();
        if (termo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome ou ID do membro.");
            return;
        }
        
        HistoricoDAO dao = new HistoricoDAO();
        listaAtual = dao.buscarPorMembro(termo);

        if (listaAtual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma atividade encontrada.");
            return;
        }

        idMembroAtual = listaAtual.get(0).getIdMembro(); 
        carregarTabela(listaAtual);
   
        
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
       if (idMembroAtual == -1) {
            JOptionPane.showMessageDialog(this, "Busque um membro antes de adicionar.");
            return;
        }

        TelaCadastroHistorico tela = new TelaCadastroHistorico(idMembroAtual);
        tela.setVisible(true);
    
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
 String termo = campoBusca.getText().trim();

    if (termo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o nome ou ID do membro.");
        return;
    }

    HistoricoDAO dao = new HistoricoDAO();
    List<Historico> listaAtual = dao.buscarPorMembro(termo);
    
    System.out.println("Resultados encontrados: " + listaAtual.size());
for (Historico h : listaAtual) {
    System.out.println("Atividade: " + h.getAtividade() + " - Data: " + h.getDataAtividade());
}


    if (listaAtual.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhuma atividade encontrada.");
        return;
    }

    
    idMembroAtual = listaAtual.get(0).getIdMembro();

    
    carregarTabela(listaAtual);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
      int linha = tabelaHistorico.getSelectedRow();
if (linha == -1) {
    JOptionPane.showMessageDialog(this, "Selecione uma atividade para excluir.");
    return;
}

if (listaAtual == null || listaAtual.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Nenhum dado carregado para excluir.");
    return;
}

int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este histórico?", "Confirmação", JOptionPane.YES_NO_OPTION);
if (confirmacao != JOptionPane.YES_OPTION) {
    return;
}

int id = listaAtual.get(linha).getId();
idMembroAtual = listaAtual.get(0).getIdMembro();

HistoricoDAO dao = new HistoricoDAO();
dao.excluir(id);


listaAtual = dao.buscarPorMembro(String.valueOf(idMembroAtual));
carregarTabela(listaAtual);

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void campoBuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBuscaFocusGained
        // TODO add your handling code here:
        if (campoBusca.getText().equals("Nome")) {
           campoBusca.setText("");
           campoBusca.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoBuscaFocusGained

    private void campoBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBuscaFocusLost
        // TODO add your handling code here:
        if (campoBusca.getText().isEmpty()) {
         campoBusca.setForeground(Color.GRAY);
         campoBusca.setText("Nome");
}
    }//GEN-LAST:event_campoBuscaFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        campoBusca.setText("Nome");
        campoBusca.setForeground(Color.GRAY);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaHistorico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHistorico;
    // End of variables declaration//GEN-END:variables
}
