/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import sistemaacademia.Treino;
import sistemaacademia.TreinoDAO;

/**
 *
 * @author FARIAS
 */
public class TelaCadastroTreino extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroTreino.class.getName());

    /**
     * Creates new form TelaCadastroTreino
     */
    private final int idMembro;
    private int idMembroAtual;

    
    public TelaCadastroTreino(int idMembro) {
        initComponents();
        this.idMembro = idMembro;
         this.idMembroAtual = idMembro;
        setLocationRelativeTo(null);
        setSize(404, 335); 
        setResizable(false); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTipo = new javax.swing.JTextField();
        campoDuracao = new javax.swing.JTextField();
        campoData = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        campoDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        campoTipo.setText("Tipo");
        campoTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTipoFocusLost(evt);
            }
        });
        getContentPane().add(campoTipo);
        campoTipo.setBounds(110, 90, 180, 22);

        campoDuracao.setText("Duração");
        campoDuracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDuracaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDuracaoFocusLost(evt);
            }
        });
        getContentPane().add(campoDuracao);
        campoDuracao.setBounds(110, 130, 180, 22);

        campoData.setText("Data");
        campoData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataFocusLost(evt);
            }
        });
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });
        getContentPane().add(campoData);
        campoData.setBounds(110, 170, 180, 22);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(150, 250, 90, 30);

        campoDescricao.setText("Descrição");
        getContentPane().add(campoDescricao);
        campoDescricao.setBounds(110, 210, 180, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/POPUP treino.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 401, 339);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String tipo = campoTipo.getText().trim();
        String data = campoData.getText().trim();
        String duracao = campoDuracao.getText().trim();
        String descricao = campoDescricao.getText().trim();

        if (tipo.isEmpty() || data.isEmpty() || duracao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        Treino h = new Treino();
        h.setTipo(campoTipo.getText());
        h.setDuracao(campoDuracao.getText());
        h.setDataInicio(campoData.getText());
        h.setDescricao(campoDescricao.getText());
        h.setIdMembro(idMembroAtual);

        new TreinoDAO().inserir(h);

        JOptionPane.showMessageDialog(this, "Treino cadastrado com sucesso!");
       

        this.dispose();
    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void campoTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTipoFocusGained
        // TODO add your handling code here:
        if (campoTipo.getText().equals("Tipo")) {
           campoTipo.setText("");
           campoTipo.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoTipoFocusGained

    private void campoTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTipoFocusLost
        // TODO add your handling code here:
        if (campoTipo.getText().isEmpty()) {
         campoTipo.setForeground(Color.GRAY);
         campoTipo.setText("Tipo");
}
    }//GEN-LAST:event_campoTipoFocusLost

    private void campoDuracaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDuracaoFocusGained
        // TODO add your handling code here:
         if (campoDuracao.getText().equals("Duração")) {
           campoDuracao.setText("");
           campoDuracao.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoDuracaoFocusGained

    private void campoDuracaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDuracaoFocusLost
        // TODO add your handling code here:
        if (campoDuracao.getText().isEmpty()) {
         campoDuracao.setForeground(Color.GRAY);
         campoDuracao.setText("Duração");
}
    }//GEN-LAST:event_campoDuracaoFocusLost

    private void campoDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFocusGained
        // TODO add your handling code here:
        if (campoData.getText().equals("Data")) {
           campoData.setText("");
           campoData.setForeground(Color.BLACK);
}
    }//GEN-LAST:event_campoDataFocusGained

    private void campoDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFocusLost
        // TODO add your handling code here:
        if (campoData.getText().isEmpty()) {
         campoData.setForeground(Color.GRAY);
         campoData.setText("Data");
}
    }//GEN-LAST:event_campoDataFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        campoTipo.setText("Tipo");
        campoTipo.setForeground(Color.GRAY);
        
        campoDuracao.setText("Duração");
        campoDuracao.setForeground(Color.GRAY);
        
        campoData.setText("Data");
        campoData.setForeground(Color.GRAY);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroTreino(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoDuracao;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
